### ISSUE TITLE
[BUG] neutrino$tickClockandCompass crash

### ISSUE THREAD

**Issue by Yucked** [FrostWizard4/Neutrino#29]
**Describe the bug**
Selected the compass which was generated when I died by one of the mods (if I'm not wrong) and it crashed the client. Crash report generated states neutrino was at fault.

Crash report: https://crashy.net/PtHiakeL6QemdlWSBouF

**Comment by srwxr-xr-x** [comment]
Can you send the crash log without crashy? it's useful but organizes data into a way that makes it hard for me to use.

**Comment by Yucked** [comment]
They have a raw version of it on there as well: https://crashy.net/PtHiakeL6QemdlWSBouF?raw

**Comment by AshrielV** [comment]
I am having this same problem

**Comment by srwxr-xr-x** [comment]
I'll take a look at it, and try to get it fixed in the next update.

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/AIfVmNDbqh

**Comment by TheRanker** [comment]
Same thing in my modpack as well .
https://pastebin.ubuntu.com/p/HSvmTSGXF5/
Older version. Still happens in latest for 1.18.1 fabric though

**Comment by srwxr-xr-x** [comment]
Provided this version which removes the broken method causing this:
[https://github.com/FrostWizard4/Neutrino/releases/tag/v0.6.8](https://github.com/FrostWizard4/Neutrino/releases/tag/v0.6.8)

**Comment by srwxr-xr-x** [comment]
Fixed in v0.6.9 by removing the Broken Clock and Compass feature.
